// Import React and Next.js Link component
import { Navbar } from "@/components/Navbar";
import { Hero } from "@/components/Hero";

export default function Home() {
  return (
    <>
      <Navbar />
      <div className="w-full flex justify-center">
        <Hero />
      </div>
      <div className="p-8">
        <h1 className="text-2xl font-bold">
          Welcome to Taj Cables and Conductors
        </h1>
        <p>Generated by create next app</p>
      </div>
    </>
  );
}
