export const images = {
  factoryPov: "/static/factory/VBV01082.jpg",
  factoryOut: "/static/factory/VBV01110.jpg",
  factoryCenter: "/static/factory/VBV01118.jpg",
  wireBetweenmachines: "/static/factory/VBV01136.jpg",
  workerWorkingWide: "/static/factory/VBV01148.jpg",
  workerWorkingNormal: "/static/factory/VBV01163.jpg",
  wirecClose1: "/static/factory/VBV01165.jpg",
  wirecClose2: "/static/factory/VBV01166.jpg",
  wireWheelWide: "/static/factory/VBV01201.jpg",
  wireWheelNormal: "/static/factory/VBV01204.jpg",
  blurWorkerLookingAway: "/static/factory/VBV01214.jpg",
  workerSafetyHat: "/static/factory/VBV01215.jpg",
  workerWorkingBetweenWires: "/static/factory/VBV01233.jpg",
  workerClapping: "/static/factory/VBV01305.jpg",
  wireTopViewDark: "/static/factory/VBV01326.jpg",
  wireTopViewLight: "/static/factory/VBV01339.jpg",
};
